### ISSUE TITLE
HTTP Checks produce NullReferenceException when they stop sending the check.

### ISSUE THREAD

**Issue by Grumblesmith** [Netuitive/netuitive-windows-agent#28]
Steps to reproduce:

1. Configure an HttpCheck against a website running on localhost.
2. Stop the local website from serving
3. Check stops being sent and errors appear in log.

Error: 
```
Exception in ReadThreadProc()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Netuitive.CollectdWin.ReadSystemChecksPlugin.CheckHttp()
   at Netuitive.CollectdWin.ReadSystemChecksPlugin.Read()
   at BloombergFLP.CollectdWin.MetricsCollector.ReadThreadProc()
```

**Comment by andrewpaine** [comment]
Closed
